### ISSUE TITLE
list all komponents when using "view komponent" without any arguments

### ISSUE THREAD

**Issue by ronnierap** [MarkHooijkaas/kisst.kreate#33]
(.venv) % kreate v k
==== view komponent =======
IndexError: list index out of range

Would be great to list all known komponents in the current setup when no komponent is given.

(.venv)  % kreate v k Deployment.main
has to be given to view details of the Deployment.main komponent.
Can we also do kreate v k Deployment to list all the deployments. When only one is in the list view details. If multiple items are still found just present the list of all Deployment's ?

**Comment by MarkHooijkaas** [comment]
I implemented this, in a even more fast way:
`view komp <str>` will search for all komponents that start with `<str>` (case insensitive)

I also added an issue for more generic alias mechanism. https://github.com/MarkHooijkaas/kreate-kube/issues/34
